name: Upload to S3
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 10.x
      - uses: chrislennon/action-aws-cli@v1.1
      - run: yarn install
      - run: yarn build
      - run: aws s3 sync dest/ s3://yamagata-cov19.m5a.jp --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
