name: Upload to S3

on:
  schedule:
    # 4時間置きに実行
    - cron: '0 */4 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup AWS
        uses: chrislennon/action-aws-cli@v1.1
      - name: Setup node
        uses: actions/setup-node@master
        with:
          node-version: 10.x
      - name: Download
        run: |
          wget -P src/.vuepress/public/ -r -l 1 https://www.pref.yamagata.jp/ou/bosai/020072/kochibou/coronavirus/coronavirus.html
      - name: Deploy
        if: always()
        run: |
          yarn install
          node test.js
          yarn build
          aws s3 sync dest/ s3://yamagata-cov19.m5a.jp --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
